audit_header: false
title: Denver Metro Real Estate Video Blog with Tom Witzel
description: Our mission at RE/MAX Alliance is to be your best resource for Denver real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from Tom Witzel, your professional Denver Real Estate Agents.
show_custom_links: true
custom_links:
  - title: New Home Builders
    url: http://www.tomwitzel.com/new-home-construction
  - title: Marketing Package
    url: http://www.tomwitzel.com/best-real-estate-marketing

client:
  name: Tom Witzel
  title: REALTOR
  license_number:
  about_markdown: |
    I’ve been a real estate professional since 1999 and am a licensed expert in the state of Colorado. In that time, I’ve studied the industry and have earned the designation of Accredited Buyers Representative, I’m a graduate of Realtor Institute, a Certified Distressed Property Expert, and a Certified Negotiation Expert. Beyond that, I belong to the National Association of Realtors, the Colorado Association of Realtors, and am a member of The Denver Metro Area Realtor Association. I specialize in helping people buy and sell homes in Thornton, Northglenn, Westminster, Broomfield, Brighton, Arvada, Parker, Aurora, and Denver. I also specialize in new home sales with production and custom home builders.
  market: Denver Metro
  brand: RE/MAX Alliance
  brokerage:
  address: '13659 East 104th Avenue Suite #100<br>Commerce City, CO 80022'
  phone: 303-808-2206
  phone_type:
  phone2:
  phone2_type:
  email: tom@tomwitzel.com
  url: http://www.tomwitzel.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.tomwitzel.com/property-search-map-on-active/type-single%20family;condo;townhouse/dsort-p/lat-39.460761-40.309868/lon-_105.997933-_102.116459

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.tomwitzel.com/property-search-map-on-active/type-single%20family;condo;townhouse/dsort-p/lat-39.460761-40.309868/lon-_105.997933-_102.116459

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: http://www.facebook.com/tomwitzelyourtrustedrealestatepartner
  linkedin_url: http://www.linkedin.com/in/tomwitzel
  gplus_url:
  youtube_url: http://www.youtube.com/user/TomWitzelColorado
  twitter_url: http://www.twitter.com/twitzelrealtor
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#0053a0'
  theme_color: '#ee3a43'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
